# Generated by Django 3.2.9 on 2022-09-15 07:34

import datetime
from django.db import migrations
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardnews',
            name='nepali_date',
            field=nepali_datetime_field.models.NepaliDateField(default=datetime.datetime.now),
        ),
    ]
