# Generated by Django 3.2.9 on 2022-09-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_nepali', '0002_standardnews_nepali_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardnews',
            name='nepali_date',
        ),
    ]
